#!/usr/bin/env sh
if [ ! -f ~/.local/share/fonts/JetBrainsMonoNerdFont-Regular.ttf ]; then
    echo "DOWNLOADING FONT"

    mkdir -p ~/.local/share/fonts/
    
    curl -o /tmp/JetBrainsMono.zip -L https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/JetBrainsMono.zip

    unzip /tmp/JetBrainsMono.zip -d ~/.local/share/fonts/

    fc-cache -vf ~/.local/share/fonts/
fi

if [ ! -f ~/.local/share/icons/Simp1e-Gruvbox-Dark/ ]; then
    echo "DOWNLOADING CURSOR THEME"

    mkdir -p ~/.local/share/icons/

    curl -o /tmp/Simp1e-Gruvbox-Dark.tar.xz -L https://www.pling.com/p/1932768/Simp1e-Gruvbox-Dark.tar.xz
    tar -xvf /tmp/Simp1e-Gruvbox-Dark.xz -C ~/.local/share/icons/
fi
