#!/usr/bin/env -S guix shell unzip -- bash

if [ ! -f ~/.local/share/fonts/JetBrainsMonoNerdFont-Regular.ttf ]; then
    echo "DOWNLOADING FONT"

    mkdir -p ~/.local/share/fonts/
    
    curl -o /tmp/JetBrainsMono.zip -L https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/JetBrainsMono.zip

    unzip /tmp/JetBrainsMono.zip -d ~/.local/share/fonts/

    fc-cache -vf ~/.local/share/fonts/
fi

if [ ! -d ~/.local/share/icons/Simp1e-Gruvbox-Dark/ ]; then
    echo "COPYING CURSOR THEME"

    cp -r ~/nix/system/hosts/t420/icons/ .local/share/icons
fi

echo "FONTS AND CURSORS INSTALLED"
